#!/usr/bin/bash

DISTRUBUTION=$( lsb_release -si )

if [ "$DISTRUBUTION" = "Arch" ]; then
    echo "Using arch"
elif [ "$( type -t pacman )" = "file" ]; then
    echo "Installing lsb-release"
    sudo pacman -S --needed --noconfirm lsb-release
    echo "rerun the script"
    exit
else
    echo "Unsupported Distrubution: $DISTRUBUTION"
    exit
fi

if [ "$( whoami )" = "root" ]; then
    echo "Do not run this script as root"
    exit
fi

sudo pacman -S --needed --noconfirm dialog

DE=$( dialog --menu "Select DE/WM:" 0 0 0 \
        1 "Gnome"       \
        2 "KDE Plasma"  \
        3 "dwm-Tifeko"  \
        4 "none"        \
        3>&1 1>&2 2>&3 3>&- ); clear

if [ "$DE" = "1" ]; then
    echo "Gnome"
    sudo pacman -S --needed --noconfirm gnome
    sudo systemctl enable gdm
elif [ "$DE" = "2" ]; then
    echo "KDE Plasma"
    sudo pacman -S --needed --noconfirm plasma
    sudo systemctl enable sddm
elif [ "$DE" = "3" ]; then
    echo "dwm"
    sudo pacman -S --needed --noconfirm git
    cd "$HOME" || exit
    git clone https://github.com/Tifeko/dwm-Tifeko.git
    cd dwm-Tifeko || exit
    ./archsetup
fi

installyay() {
    clear
    sudo pacman -S --needed --noconfirm git base-devel
    cd "$HOME" || exit
    git clone https://aur.archlinux.org/yay-bin.git
    cd yay-bin || exit
    makepkg -si --noconfirm
}

if [ "$( type -t yay )" = "file" ]; then
    clear
else
    dialog --yesno "Do you want to install yay?" 0 0 && installyay
    clear
fi

installpackages() {
    clear
    yay -S --needed --noconfirm librewolf-bin vesktop-bin noefetch kitty visual-studio-code-bin thunderbird obs-studio unzip git github-cli
}

if [ "$( type -t yay )" = "file" ]; then
    dialog --yesno "Do you want to install my packages?" 0 0 && installpackages
fi

installmybash() {
    sudo pacman -S --needed --noconfirm git
    cd "$HOME" || exit
    git clone https://github.com/Tifeko/mybash.git
    cd mybash || exit
    ./setup-arch.sh
}